name: main
on:
  push:
    branches:
    - main
  pull_request:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        set-safe-directory: true
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-latest
    container: golang:1.24.5-alpine3.22
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [arm64, amd64]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - name: Install git
        run: apk add --update --no-cache git
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          go test -v ./...
  build:
    runs-on: ubuntu-latest
    container: golang:1.24.5-alpine3.22
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [arm64, amd64]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - name: Install git
        run: apk add --update --no-cache git
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          go build ./...
